# Pipes â•°â”€ â•­â”€
# Powerline symbols Â î‚° î‚± î‚² î‚³ î‚´ î‚µ î‚¶ î‚· î‚¸ î‚¹ î‚º î‚» î‚¼ î‚½ î‚¾ î‚¿ îƒ€ îƒ îƒ‚ îƒƒ îƒ„ îƒ… îƒ† îƒ‡ îƒˆ îƒŠ  îƒŒ îƒ îƒ îƒ îƒ îƒ‘ îƒ” îƒ’ 
# Wedges ğŸ­§ğŸ­’ ğŸ­£ğŸ­§ğŸ­“
# Random noise ğŸ¬–ğŸ¬¥ğŸ¬”ğŸ¬—
# Cool stuff ó°œ¥ î©± ï‹ ï€

add_newline = false

format = """
$username $directory $git_branch
$character"""

[character]
success_symbol = "[  â•°â”€ï‹](bold fg:blue)"
error_symbol = "[ â¨¯â•°â”€ï‹](bold fg:red)"

[package]
disabled = true

[git_branch]
style = "bg: cyan"
symbol = "ó°˜¬"
truncation_length = 12
truncation_symbol = ""
format = "ï„… [î‚¶](bold fg:cyan)[$symbol $branch(:$remote_branch)](fg:black bg:cyan)[î‚´ ](bold fg:cyan)"

[git_commit]
commit_hash_length = 4
tag_symbol = "ï’¶ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[îŠ› PICKING](bold red)"

[git_status]
conflicted = " ï€¤ "
ahead = " î¸· "
behind = " î¸¸ "
diverged = " ó±¡· "
untracked = " ó±ª— "
stashed = " îµµ "
modified = " ïŸ "
staged = '[++\($count\)](green)'
renamed = " î¸¼ "
deleted = " ï‡¸ "

[hostname]
ssh_only = false
format =  "[â€¢$hostname](bg:cyan bold fg:black)[î‚´](bold fg:cyan)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = true
time_format = "%H:%M"
style = "bold bg:cyan fg:black"
format = "(bold fg:cyan)[ ï€— $time]($style)[î‚´](bold fg:cyan)"

[username]
style_user = "bold bg:blue fg:black"
style_root = "red bold"
format = "[î‚¶](bold fg:blue)(bold fg:blue)[$user]($style)[î‚´](bold fg:blue)"
disabled = false
show_always = true

[directory]
home_symbol = " ï€• "
read_only = " ï€£ "
style = "bg:cyan fg:black"
truncation_length = 6
truncation_symbol = " â€¢â€¢â€¢/"
format = 'ï„„ [î‚¶](bold fg:cyan)[ó°‰‹ $path]($style)[î‚´](bold fg:cyan)'


[directory.substitutions]
"Desktop" = " ï’© "
"Documents" = " ï…› "
"Downloads" = " ï‰ "
"Music" = " ó°ˆ "
"Pictures" = " ï€¾ "
"Videos" = " ï”¬ "
"GitHub" = " ó°Š¤ "

[cmd_duration]
disabled = false
min_time = 0
format = '[î‚¶](bold fg:yellow)[ï€— $duration](bold bg:yellow fg:black)[î‚´](bold fg:yellow)'
